### ISSUE TITLE
Which one is the same within all groups, the numerator or the denominator?

### ISSUE THREAD

**Issue by 1-2-3-4-0** [Adamdad/kat#15]
You mentioned in the paper that the denominator is the same for all groups, but the code seems to suggest the opposite.
![图片](https://github.com/user-attachments/assets/0b27d331-5490-45f6-b65b-943c3d890002)
In the code, the numerators are the same for all groups.
![图片](https://github.com/user-attachments/assets/f47488d8-1eff-4e23-ba38-1dcf81ff2136)

**Comment by Adamdad** [comment]
@1-2-3-4-0 ！！！extrewly sorry for the typo in the paper！i willrevise and update the arxiv version right now！
