### ISSUE TITLE
i can't import kat_rational_cu

### ISSUE THREAD

**Issue by zack5582** [Adamdad/kat#17]
![屏幕截图 2024-10-26 133223](https://github.com/user-attachments/assets/76bcf848-15cd-4d02-9569-312f44b354ea)

**Comment by zack5582** [comment]
I follow the steps in the readme.md,but seems the package is not installed correctly.

**Comment by Adamdad** [comment]
Hello @zack5582 ，How did you install the environment? Did you install `Adamdad/rational_kat_cu`? Can you give all the package information of your environment?

**Comment by zack5582** [comment]
Hello! Yes, I did set up the environment as required. Here's a summary of the package information.
[packages.txt](https://github.com/user-attachments/files/17610022/packages.txt)

**Comment by Adamdad** [comment]
Sorry but I do not see that you installed `kat-rational` in the env?

**Comment by zack5582** [comment]
Yes, that's the problem, but i'm sure i follow the steps and successfully installed  kat-rational-0.3.
![image](https://github.com/user-attachments/assets/c71dfe22-a48d-45dc-b7dd-7c851c2f8048)

**Comment by Adamdad** [comment]
Are you sure you're using the same environment where you installed the packages? Sometimes people use a different environment than the one in which they installed their packages.

**Comment by zack5582** [comment]
Thank you for reminding me，i tested on my computer and  it's successfully installed, the problem is resulted by my environment setting.
