### ISSUE TITLE
ModuleNotFoundError: No module named 'kat_rational.rational_cuda_a_1dgroup'

### ISSUE THREAD

**Issue by csguoh** [Adamdad/kat#2]
Hi, authors.

Thanks for sharing this awesome work. When I install the `kat_rational` under the instruction of README.md, I meet some error with the code `from kat_rational import KAT_Group` :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rational_kat_cu/kat_rational/__init__.py", line 1, in <module>
    from .kat_1dgroup import rational_1dgroup, KAT_Group
  File "/home/rational_kat_cu/kat_rational/kat_1dgroup.py", line 6, in <module>
    from .rational_cuda_a_1dgroup import Rational_CUDA_A_1DGroup
ModuleNotFoundError: No module named 'kat_rational.rational_cuda_a_1dgroup'
```

Could you help solve this problem? Are there some CUDA version requirements for the `kat_rational`?

**Comment by Adamdad** [comment]
Sorry for the mistake, just fix this. Can git clone again and try

**Comment by Adamdad** [comment]
can git clone https://github.com/Adamdad/rational_kat_cu again and pip install -e .

**Comment by csguoh** [comment]
Thanks for your help. This problem has been successfully fixed :)
