### ISSUE TITLE
Unsupported nonlinearity swish

### ISSUE THREAD

**Issue by LQchen1** [Adamdad/kat#20]
My version of torch is the same as yours, 2.0.1, but I noticed some errors when running, knn.init.kaiming_normal_ does not include swish activation function.
![image](https://github.com/user-attachments/assets/72d2f551-1ad0-4b20-a74f-b345f3214093)
![image](https://github.com/user-attachments/assets/25485c4c-1f53-45df-982d-8bfafb2a2588)

**Comment by Tony-Y** [comment]
https://github.com/Adamdad/kat/blob/ecb0eb76bf17c701acdf4978f95c490d767e4e87/katransformer.py#L43

https://github.com/Adamdad/kat/blob/ecb0eb76bf17c701acdf4978f95c490d767e4e87/katransformer.py#L85-L86

https://github.com/Adamdad/kat/blob/ecb0eb76bf17c701acdf4978f95c490d767e4e87/katransformer.py#L101

**Comment by LQchen1** [comment]
Thank you for reminding, May good people befree from mishap salltheirlives
