### ISSUE TITLE
 in katransformer.py, the line from kat_rational import KAT_Group fails to find the corresponding file

### ISSUE THREAD

**Issue by Cyc-InGitHub** [Adamdad/kat#4]
Thank you very much for your sharing. However, I encountered an issue while using it: in katransformer.py, the line from kat_rational import KAT_Group fails to find the corresponding file. I'm wondering if you've experienced the same issue.

**Comment by Adamdad** [comment]
Hello @Cyc-InGitHub ,Have you install the CUDA extension already? `kat_rational` can be imported once the CUDA extension is installed https://github.com/Adamdad/rational_kat_cu

**Comment by Cyc-InGitHub** [comment]
I'll try again. thank you for your answer. have a good day!
