### ISSUE TITLE
[Errno 2] No such file or directory: ':/usr/local/cuda:/usr/local/cuda/bin/nvcc'

### ISSUE THREAD

**Issue by YutingLi0606** [Adamdad/kat#6]
python setup.py develop did not run successfully.
│ exit code: 1
╰─> [35 lines of output]
    running develop
    /data/liyuting/miniconda3/envs/k/lib/python3.9/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /data/liyuting/miniconda3/envs/k/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    writing kat_rational.egg-info/PKG-INFO
    writing dependency_links to kat_rational.egg-info/dependency_links.txt
    writing top-level names to kat_rational.egg-info/top_level.txt
    reading manifest file 'kat_rational.egg-info/SOURCES.txt'
    writing manifest file 'kat_rational.egg-info/SOURCES.txt'
    running build_ext
    error: [Errno 2] No such file or directory: ':/usr/local/cuda:/usr/local/cuda/bin/nvcc'
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

Where to set this path?

**Comment by Adamdad** [comment]
Hello @YutingLi0606 , 
A general solution to your issue can be found here: https://github.com/NVIDIA/apex/issues/368.

In short, you need to set the `CUDA_HOME` environment variable to point to your CUDA installation. You can do this by running:

```shell
export CUDA_HOME=/usr/local/cuda
```

Please note that the path `/usr/local/cuda` may vary depending on your CUDA version and setup. Make sure to replace it with the correct path if your CUDA is installed elsewhere.

**Comment by YutingLi0606** [comment]
Thank you~
